### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by AbooMinister25** [AbooMinister25/code-jam#9]
This issue will detail the tasks we need to complete in order to get an MVP (minimal viable product).

## Backend
- [x] Set up websocket route for communicating with frontend.
- [x] Map drawn out and movement implemented.
- [x] Game mechanics (scoring, progression, etc).
- [x] Multiple connections (might require the introduction of accounts)

## Client
- [x] Mockup layout for client.
- [x] Set up connection with the backend through websockets.
- [x] Handle incoming map and player data.

**Comment by HourGlss** [comment]
This issue will detail the tasks we need to complete in order to get an MVP (minimal viable product).

## Backend
- [x] Main route (/) which will serve static content.
- [x] Set up websocket route for communicating with frontend.
- [ ] Map drawn out
- [x] Movement implemented.
- [ ] a leveling system for the player
- [ ] getting more skills as the player levels
- [ ] clearing mob corpses
- [ ] respawning mobs
- [ ] Game mechanics (scoring, progression, etc).
- [ ] Multiple connections (might require the introduction of accounts)

### Backend Stretch
- [ ] mutliple mob types ( 2-6)
- [ ] 3-5 more skills
- [ ] security
- [ ] deployment to a webserver

## Client
- [x] Mockup layout for client.
- [x] Set up connection with the backend through websockets.
- [ ] Handle incoming map and player data.

### Stretch Client
- [ ] security

**Comment by BautistaDalmasso** [comment]
## Backend
- [x] Main route (/) which will serve static content.
- [x] Set up websocket route for communicating with frontend.
- [ ] Map drawn out
- [x] Movement implemented.
- [x] a leveling system for the player
- [ ] getting more skills as the player levels  -> I vote we ditch this, our "bug" is more notorious when the player has many skills that are messed around with. (basically give the player many abilities from the get-go)
- [x] clearing mob corpses
- [ ] respawning mobs  -> I vote we ditch this. (For the sake of simplicity... we don't have many hours left)
- [ ] Game mechanics (scoring, progression, etc). -> I vote we ditch this. (For the sake of simplicity... we don't have many hours left)
- [x] Multiple connections (might require the introduction of accounts)
